sudo: required 

language: node_js 

services:
    - docker
before_install:
    - docker build -t deepakarora2010/task-manager -f Dockerfile.dev .
script:
    - npm test
    - npm run build
  

