sudo: true 

language: node_js 

services:
    - docker
before_install:
    - docker build -t deepakarora2010/task-manager -f Dockerfile.dev .
script:
  - docker run -e CI=true USERNAME/docker-react npm run test
  

