sudo: required

language: node_js

node_js:
  - node
services:
  - docker
before_install:
  - docker build -t deepakarora2010/task-manager -f Dockerfile.dev .
    
script:
  - CI=false npm run build

