sudo: required

language: node_js

node_js:
  - node
services:
  - docker
before_install:
  - docker build -t deepakarora2010/task-manager -f Dockerfile.dev .
    
script:
  - CI=false npm run build

deploy:
  provider: elasticbeanstalk
  region: "ap-south-1"
  app: "taskmanager2"
  env: "Taskmanager2-env"
  bucket_name: "elasticbeanstalk-ap-south-1-878656876834"
  bucket_path: "taskmanager2"
  on:
    branch: main

